### ISSUE TITLE
Error: The provided sha-commit is invalid.

### ISSUE THREAD

**Issue by fahadshery** [iot-salzburg/gpu-jupyter#152]
## Issue Description

**Describe the issue**
I have created my own docker-compose file:
```
---
services:
  gpu-jupyter:
    container_name: gpu-jupyter
    build: .build
    volumes:
      - ./data:/home/jovyan/work
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gpu-jupyter.rule=Host(`jupyter.local.example.com`)"
      - "traefik.http.routers.gpu-jupyter.entrypoints=https"
      - "traefik.http.routers.gpu-jupyter.tls=true"
      - "traefik.http.routers.gpu-jupyter.tls.certresolver=cloudflare"
      - "traefik.http.services.gpu-jupyter.loadbalancer.server.port=8888"
      - "traefik.http.routers.gpu-jupyter.middlewares=default-headers@file"
    # enable sudo permissions
    user: "root"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"] # select one GPU
networks:
  traefik:
    external: true
```
It works fine but I am unable to generate custom image e.g. I wish to install nltk package in the `custom/usefulpackages.Dockerfile` file.  
When I try to `generate` the `DockerFile` it gives an error: 
```
admin@datascience:~/datascience/gpu-jupyter$ ./generate-Dockerfile.sh
Set docker-stacks to commit 'e838ff397a2d9c2ad0faae051ef0ec4f20732320'.
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>


Error: The provided sha-commit is invalid.
Usage: ./generate-Dockerfile.sh -c [sha-commit] # set the head commit of the docker-stacks submodule (https://github.com/jupyter/docker-stacks/commits/master).
Exiting
```
**To Reproduce**
1. Add `nltk` package name to `custom/usefulpackages.Dockerfile` file.  
2. `git checkout v1.7_cuda-12.2_ubuntu-22.04`
3. `./generate-Dockerfile.sh -c '823cf92db4ede8f5a4836c5b7ea761e4ea3923c7'`

**Expected Behavior**

**Screenshots**
Here are the commit hashes I tried:
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/4a330aec-ae85-467c-8627-ddc74cf52229">
 

## Environment

**Operating System:**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"

**NVIDIA GPU and CUDA version Details:**
Provide details about the NVIDIA GPU, driver versions and CUDA version you are using (e.g., model, driver version `nvidia-smi` and `nvcc --version`).

**GPU-Jupyter Version:**
```
nvidia-smi
Sat Aug 31 08:43:05 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  GRID P40-24Q                   On  | 00000000:01:00.0 Off |                  N/A |
| N/A   N/A    P8              N/A /  N/A |    358MiB / 24576MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    775690      C   python                                      210MiB |
|    0   N/A  N/A    891724      C   python                                      148MiB |
+---------------------------------------------------------------------------------------+
```

**Docker command and parameters:**
docker compose up -d --build --force-recreate --remove-orphans

**Browser (if applicable):**
Safari

## Additional Context

Add any other context about the problem here, such as specific configurations or circumstances under which the bug occurs.

---

*Please ensure that you have checked the existing issues to avoid duplicates. Thank you for contributing to making GPU-Jupyter better!*
